dist: xenial
language: generic

script:
  - ./tests/test_init.sh
  - ./tests/test_init-files.sh
  - ./tests/test_simple.sh
  - ./tests/test_advanced.sh
  - ./tests/test_version_attributes.sh
  - ./tests/test_multiple_MKIAPP_FILE.sh
